title: FASHIONISTA BLOG
date: 2021-09-20
author: GithubUser
email: kayode.ayiloye.1016@fuoye.edu.ng
description: > # this means to ignore newlines until "baseurl:"
  this blog is all about Fashion designing, trending gists, latest design, pattern drafting, and online class.
# social links
twitter_username: Ayiloyetimothy # DO NOT include the @ character, or else the build will fail!
github_username:  KAYUS-COUTURE # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
